package com.electronic.model;

public class OrderAddr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_addr.addr_id
     *
     * @mbggenerated Wed Nov 22 13:16:56 GMT+08:00 2017
     */
    private String addr_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_addr.order_id
     *
     * @mbggenerated Wed Nov 22 13:16:56 GMT+08:00 2017
     */
    private String order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_addr.province
     *
     * @mbggenerated Wed Nov 22 13:16:56 GMT+08:00 2017
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_addr.city
     *
     * @mbggenerated Wed Nov 22 13:16:56 GMT+08:00 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_addr.area
     *
     * @mbggenerated Wed Nov 22 13:16:56 GMT+08:00 2017
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_addr.detail_addr
     *
     * @mbggenerated Wed Nov 22 13:16:56 GMT+08:00 2017
     */
    private String detail_addr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_addr.addr_id
     *
     * @return the value of order_addr.addr_id
     *
     * @mbggenerated Wed Nov 22 13:16:56 GMT+08:00 2017
     */
    public String getAddr_id() {
        return addr_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_addr.addr_id
     *
     * @param addr_id the value for order_addr.addr_id
     *
     * @mbggenerated Wed Nov 22 13:16:56 GMT+08:00 2017
     */
    public void setAddr_id(String addr_id) {
        this.addr_id = addr_id == null ? null : addr_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_addr.order_id
     *
     * @return the value of order_addr.order_id
     *
     * @mbggenerated Wed Nov 22 13:16:56 GMT+08:00 2017
     */
    public String getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_addr.order_id
     *
     * @param order_id the value for order_addr.order_id
     *
     * @mbggenerated Wed Nov 22 13:16:56 GMT+08:00 2017
     */
    public void setOrder_id(String order_id) {
        this.order_id = order_id == null ? null : order_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_addr.province
     *
     * @return the value of order_addr.province
     *
     * @mbggenerated Wed Nov 22 13:16:56 GMT+08:00 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_addr.province
     *
     * @param province the value for order_addr.province
     *
     * @mbggenerated Wed Nov 22 13:16:56 GMT+08:00 2017
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_addr.city
     *
     * @return the value of order_addr.city
     *
     * @mbggenerated Wed Nov 22 13:16:56 GMT+08:00 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_addr.city
     *
     * @param city the value for order_addr.city
     *
     * @mbggenerated Wed Nov 22 13:16:56 GMT+08:00 2017
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_addr.area
     *
     * @return the value of order_addr.area
     *
     * @mbggenerated Wed Nov 22 13:16:56 GMT+08:00 2017
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_addr.area
     *
     * @param area the value for order_addr.area
     *
     * @mbggenerated Wed Nov 22 13:16:56 GMT+08:00 2017
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_addr.detail_addr
     *
     * @return the value of order_addr.detail_addr
     *
     * @mbggenerated Wed Nov 22 13:16:56 GMT+08:00 2017
     */
    public String getDetail_addr() {
        return detail_addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_addr.detail_addr
     *
     * @param detail_addr the value for order_addr.detail_addr
     *
     * @mbggenerated Wed Nov 22 13:16:56 GMT+08:00 2017
     */
    public void setDetail_addr(String detail_addr) {
        this.detail_addr = detail_addr == null ? null : detail_addr.trim();
    }
}