/**
 * <p>Copyright: Copyright (c) 2017</p>
 * <p>Company: </p>
 */
package com.electronic.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 * .
 * 
 * @author daimb17192
 * @date 2017年11月23日 下午12:59:35
 * @since 1.0
 */
public class OrderDetail {
    private String user_name;

    private String mobile_tel;

    private String password;

    private String telphone;

    private String address;
    
    private String user_id;
    
    private BigDecimal dealPrice;
    
    private String orderId;

    private String goodId;
    
    private Date order_time;

    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_addr.addr_id
     *
     * @mbggenerated Wed Nov 22 13:16:56 GMT+08:00 2017
     */
    private String addr_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_addr.order_id
     *
     * @mbggenerated Wed Nov 22 13:16:56 GMT+08:00 2017
     */
    private String order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_addr.province
     *
     * @mbggenerated Wed Nov 22 13:16:56 GMT+08:00 2017
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_addr.city
     *
     * @mbggenerated Wed Nov 22 13:16:56 GMT+08:00 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_addr.area
     *
     * @mbggenerated Wed Nov 22 13:16:56 GMT+08:00 2017
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_addr.detail_addr
     *
     * @mbggenerated Wed Nov 22 13:16:56 GMT+08:00 2017
     */
    private String detail_addr;

    public String getUser_name() {
        return user_name;
    }

    public void setUser_name(String user_name) {
        this.user_name = user_name;
    }

    public String getMobile_tel() {
        return mobile_tel;
    }

    public void setMobile_tel(String mobile_tel) {
        this.mobile_tel = mobile_tel;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getTelphone() {
        return telphone;
    }

    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public BigDecimal getDealPrice() {
        return dealPrice;
    }

    public void setDealPrice(BigDecimal dealPrice) {
        this.dealPrice = dealPrice;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getGoodId() {
        return goodId;
    }

    public void setGoodId(String goodId) {
        this.goodId = goodId;
    }

    public String getAddr_id() {
        return addr_id;
    }

    public void setAddr_id(String addr_id) {
        this.addr_id = addr_id;
    }

    public String getOrder_id() {
        return order_id;
    }

    public void setOrder_id(String order_id) {
        this.order_id = order_id;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getArea() {
        return area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public String getDetail_addr() {
        return detail_addr;
    }

    public void setDetail_addr(String detail_addr) {
        this.detail_addr = detail_addr;
    }

    public Date getOrder_time() {
        return order_time;
    }

    public void setOrder_time(Date order_time) {
        this.order_time = order_time;
    }
}
