package com.electronic.dao;

import com.electronic.model.OrderAddr;

public interface OrderAddrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_addr
     *
     * @mbggenerated Wed Nov 22 13:15:35 GMT+08:00 2017
     */
    int insert(OrderAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_addr
     *
     * @mbggenerated Wed Nov 22 13:15:35 GMT+08:00 2017
     */
    int insertSelective(OrderAddr record);
}